---
title: "229E_astro_Infection_differential_expression"
author: "Lucy"
date: "2023-10-01"
output: html_document
---


### Load librarys
```{r}
# install.packages("datawizard")

library(readr)
library(knitr)
library(tidyverse)
library(GEOquery)
library(limma)
library(statmod)
library(ggplot2)
library(datawizard)
library(reshape2)
library(ggplot2)
library(ggfortify)
```

###import data
```{r}
#protein data
infec_data_raw <- read_tsv(file = '../data/combined_protein_229E_astro_infection_time_course.tsv')

nrow(infec_data_raw)
#meta data
meta_data <- read_tsv(file = '../data/experiment_annotation_229E_astro_infection_time_course_metadata.tsv')
```

###pre-process/cleaning data:
####1. remove contamination
####2. remove unnecessary columns
####3. log transformation if required
####4. remove lowly expressed proteins
```{r}
#1. remove contamination
infec_data_wo_contam <- infec_data_raw[- grep("contam_sp", infec_data_raw$Protein),]

#2. remove unnecessary columns
infec_data_shorten <- select(infec_data_wo_contam, Protein, "Protein ID", "Entry Name", Description, contains("Total Intensity"))
infec_data_shorten[infec_data_shorten == 0] <- NA

#3. log transformation

#this example shows that the data requires log transformation (not a bell shaped curve). 
# six_hpi1 <- hist(infec_data_shorten$X215_LucyC_6hpi1_100ng_1.Total.Spectral.Count,
# main="Protein Expression Histogram",
# xlab="Expression",
# xlim=c(0,100),
# col="darkmagenta",
# breaks = 1000)

infec_data_numeric <- infec_data_shorten %>% select(contains("Total Intensity"))
rownames(infec_data_numeric) <- infec_data_shorten$Protein
infec_data_logged <- log2(infec_data_numeric)
rownames(infec_data_logged) <- infec_data_shorten$Protein


#4. remove lowly expressed proteins
#convert "-inf" to "NA"
infec_data_logged[infec_data_logged == "-Inf"] <- NA

#make a new column counting the number of "NA" values
count <- rowSums(is.na(infec_data_logged))
data.log.filt <- data.frame(cbind(infec_data_logged, "Count" = count))

#Adjust the threshold at your discretion. 
#Here, I am allowing up to 75% of protein observations to be "NA"
data.log.filt <- subset(data.log.filt, Count < ncol(infec_data_logged)*0.75)
data.log.filt <- subset(data.log.filt, select = -c(Count)) #Remove count variable
```

## Without Log transform (For PCA)
```{r}
count <- rowSums(is.na(infec_data_numeric))
data.filt <- data.frame(cbind(infec_data_numeric, "Count" = count))

data.filt <- subset(data.filt, Count < ncol(infec_data_numeric)*0.75)
data.filt <- subset(data.filt, select = -c(Count))

```

```{r}

data.filt.pca <- t(data.filt) %>% as.data.frame()

## replace NA with 0 because that should mean 0 spectral count
data.filt.pca[is.na(data.filt.pca)] <- 0

## A way you can check which column has all the same values (if any)
# which(apply(data.filt.pca, 2, var)==0)

# data.filt.pca = data.filt.pca %>% select(-c(rowname))

data.filt.pca %>% head()

p <- prcomp(data.filt.pca, scale = TRUE)

data.filt.pca = rownames_to_column(data.filt.pca)
data.filt.pca$hpi = c(6, 6, 6, 12, 12, 12, 24, 24, 24, 48, 48, 48, 96, 96, 0, 0, 0)
data.filt.pca$hpi = data.filt.pca$hpi %>%  as.character()   # this makes the colour scale not an idiot

autoplot(p, data=data.filt.pca, color = "hpi")

```


###quality control
```{r}
#histogram

# first, transpose data to standardize by protein
# (by default, the standardize() function will calculate z scores by column,
# so we want our proteins as columns now
data.t <- data.frame(t(data.filt))
data.t.z <- standardize(data.t)

# Now, we need the data in long-form (melted) for making the heatmap.
# we want to bind the sample metadata to this matrix ahead of melting
# First make sure the protein data and the metadata are ordered the same
rownames(data.t.z)==meta_data$sample #check

# The order is not the same. Order both objects and try again
meta_data.order <- meta_data[order(meta_data$sample),]

#I am sure you could order the rownames directly too, but here I move the sample names into a column, order it, and move it back to rownames
data.t.z <- rownames_to_column(data.t.z) 
data.t.z <- data.t.z[order(data.t.z$rowname),]
rownames(data.t.z) <- NULL #uninitialize rownames to accept new names
data.t.z <- column_to_rownames(data.t.z, var = "rowname")
rownames(data.t.z) == meta_data.order$sample #Success!

#now that it's ordered, bind metadata variables to protein data
data.t.z <- data.frame(cbind(data.t.z, meta_data.order))

#define vector for id.vars
vars <- colnames(meta_data.order)
data.t.z.melt <- melt(data.t.z, id.vars = vars, value.name = "Z.score", variable.name = "Protein")
head(data.t.z.melt)

ggplot(data.t.z.melt, aes(x = condition, y = Protein, fill = Z.score)) +
  geom_tile()+
  scale_fill_gradient2(low = "#0571b0", mid = "white", high = "#ca0020",
                       name = "Z score", limits = c(-4,4),na.value = "grey")+
  theme_bw()+
  theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = -50, hjust = 0, size = 6, color = "black"),
        plot.background = element_blank(),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "top")+
  scale_y_discrete(expand = c(0,0)) + 
  scale_x_discrete(expand = c(0,0))  

#data look uniform without major outliers

```

```{r}
# check for data quality with scattered plots

histogram_log_data_sample <- data.log.filt %>%  select("X215_LucyC_6hpi1_100ng_1.Total.Intensity")

histogram_log_data_sample %>% head()

ggplot(histogram_log_data_sample, aes(x=X215_LucyC_6hpi1_100ng_1.Total.Intensity)) + geom_histogram()

histogram_log_data <- data.frame(t(data.log.filt)) %>%  select(0:1)

head(histogram_log_data)

ggplot(histogram_log_data, aes(x=sp.A0A0B4J2D5.GAL3B_HUMAN)) + geom_histogram()

library(GGally)


data.filt
ggpairs(data.log.filt, columns = c(1, 4, 6))
ggpairs(data.log.filt, columns = c(4, 5, 6))

```

###limma differential analysis
```{r}
# colnames(data.filt) == meta_data.order$sample #if false, order them
colnames(data.log.filt) == meta_data.order$sample #if false, order them
meta_data.order$hpi <- c(6, 6, 6, 12, 12, 12, 24, 24, 24, 48, 48, 48, 96, 96, 0, 0, 0)
desMat <- model.matrix(~ hpi, meta_data.order)


#Call limma
fit <- lmFit(data.log.filt, desMat)
colnames(fit)

tmp <- eBayes(fit)
topTable(tmp, coef = "hpi")

limma.results <- topTable(tmp, n = Inf)
sig.prots <- subset(limma.results, adj.P.Val < 0.05)
head(sig.prots)

head(coef(fit))

```

```{r}
#sig.prots_0.01 <- subset(limma.results, adj.P.Val < 0.01)

sig.prots <- rownames_to_column(sig.prots, "Protein")

head(sig.prots)

joined <- left_join(sig.prots, infec_data_shorten, by="Protein")

joined <- joined[-8,]

#joined[is.na(joined)] <- 0

joined$avg_00hpi <- rowMeans(joined[grep("LucyC_m", colnames(joined))])
joined$avg_06hpi <- rowMeans(joined[grep("6hpi", colnames(joined))])
joined$avg_12hpi <- rowMeans(joined[grep("12hpi", colnames(joined))])
joined$avg_24hpi <- rowMeans(joined[grep("24hpi", colnames(joined))])
joined$avg_48hpi <- rowMeans(joined[grep("48hpi", colnames(joined))])
joined$avg_96hpi <- rowMeans(joined[grep("96hpi", colnames(joined))])


data_to_plot = joined[grep("avg_|Description|adj.P.Val", colnames(joined))]

data_to_plot <- data_to_plot %>% pivot_longer(cols = starts_with("avg"), names_to = "condition", values_to = "intensity") 

data_to_plot$condition[data_to_plot$condition == "avg_00hpi"] <- 0
data_to_plot$condition[data_to_plot$condition == "avg_06hpi"] <- 6
data_to_plot$condition[data_to_plot$condition == "avg_12hpi"] <- 12
data_to_plot$condition[data_to_plot$condition == "avg_24hpi"] <- 24
data_to_plot$condition[data_to_plot$condition == "avg_48hpi"] <- 48
data_to_plot$condition[data_to_plot$condition == "avg_96hpi"] <- 96

data_to_plot$condition <- as.numeric(data_to_plot$condition)


#top_20_proteins$condition <- factor(top_20_proteins$condition, c("avg_0hpi", "avg_6hpi", "avg_12hpi", "avg_24hpi", "avg_48hpi", "avg_96hpi"))
#top_20_proteins$Description <- as.factor(top_20_proteins$Description)

data_to_plot %>% ggplot(aes(x=condition, y=intensity, color = Description)) + geom_point() + geom_line() + labs(x="Hours Post Infection (hpi)", y = "Protein Abundance")

str_sort(unique(data_to_plot$condition))
```

```{r}
#96hpi vs mock volcano plots

# volcano_96_mock <- meta_data.order %>% tail(5)
# desMat_96_mock <- model.matrix(~ 0 + hpi, volcano_96_mock)
# 
# head(data.filt)
# 
# data.filt_96_mock <- data.filt %>% select("X231_LucyC_96hpi1_100ng_1.Total.Intensity":"X236_LucyC_m48_100ng_3.Total.Intensity")
# 
# #Call limma
# fit_96_mock <- lmFit(data.filt_96_mock, desMat_96_mock)
# colnames(fit_96_mock)
# 
# tmp_96_mock <- eBayes(fit_96_mock)
# topTable(tmp_96_mock, coef = "hpi")
# 
# limma.results_96_mock <- topTable(tmp_96_mock, n = Inf)
# sig.prots_96_mock <- subset(limma.results_96_mock, adj.P.Val < 0.05)
# 
# ggplot(data=limma.results_96_mock, aes(x=logFC, y=-log10(adj.P.Val))) + geom_point() + theme_minimal()
# 
# ggplot(data=sig.prots, aes(x=logFC, y=-log10(adj.P.Val), col=diffexpressed, label=delabel)) + 
#     geom_point() + 
#     theme_minimal() +
#     geom_text()

library(ggrepel)


# The significantly differentially expressed genes are the ones found in the upper-left and upper-right corners.
# Add a column to the data frame to specify if they are UP- or DOWN- regulated (log2FoldChange respectively positive or negative)



# add a column of NAs
limma.results$diffexpressed <- "NO"
# if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
limma.results$diffexpressed[limma.results$logFC > 0 & limma.results$adj.P.Val < 0.05] <- "UP"
# if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
limma.results$diffexpressed[limma.results$logFC < 0 & limma.results$adj.P.Val < 0.05] <- "DOWN"

# protein labels
limma.results <- rownames_to_column(limma.results, "Protein")

limma.results$delabel <- NA
limma.results$delabel[limma.results$diffexpressed != "NO"] <- limma.results$Protein[limma.results$diffexpressed != "NO"]

# Re-plot but this time color the points with "diffexpressed"
ggplot(data=limma.results, aes(x=logFC, y=-log10(adj.P.Val), col=diffexpressed, label=delabel)) + geom_point() + theme_minimal() + geom_text_repel() +
         scale_color_manual(values=c("blue", "black", "red")) +
   #      geom_vline(xintercept=0, col="gray") +
        geom_hline(yintercept=-log10(0.05), col="gray")


volcanoplot(fit = tmp,coef = 2)

```

