# Trying my best

```{r}
library("DEP")
library("dplyr")
library(readr)
library(knitr)
library(tidyverse)
library(GEOquery)
library(limma)
library(statmod)
library(ggplot2)
library(datawizard)
library(reshape2)
library(ggplot2)
library(ggfortify)
```

```{r}
MDAMB_proteins <- read_tsv(file = '../data/combined_protein_reMDAMB_fixed.tsv')

#meta data
MDAMB_meta_data <- read_tsv(file = '../data/experiment_annotation_reMDAMB_fixed.tsv')
```

```{r}
MDAMB_remove_contam <- MDAMB_proteins[- grep("contam_sp", MDAMB_proteins$Protein),]

MDAMB_shorten <- select(MDAMB_remove_contam, Protein, "Protein ID", "Entry Name", Description, contains("LFQ"))


names(MDAMB_shorten)[names(MDAMB_shorten) == 'Protein ID'] <- 'Protein.ID'

MDAMB_shorten = data.frame(MDAMB_shorten)
```

## Data Preparation

```{r}
MDAMB_shorten$Protein %>% duplicated() %>% any()
```

Since this is FALSE, we don't need to drop any here.

```{r}
## Split the Protein name by delimiter "|"
MDAMB_shorten <- separate_wider_delim(MDAMB_shorten, cols=Protein, delim = "|", names = c("first", "second", "third"))
MDAMB_shorten <- separate_wider_delim(MDAMB_shorten, cols = third, delim = "_", names= c("name", "human"))
MDAMB_shorten <- MDAMB_shorten %>% select(-c("first", "second", "human"))

data_unique <- make_unique(MDAMB_shorten, "name", "Protein.ID")
```

## Make SummarizedExperiment Object

```{r}
LFQ_columns <- grep("LFQ", colnames(data_unique))
```

```{r}
UbiLength_ExpDesign
```

```{r}
MDAMB_metadata_for_exp_design = MDAMB_meta_data |> select(-c(file, sample))

MDAMB_metadata_for_exp_design = MDAMB_metadata_for_exp_design |> rename_("label" = "sample_name")

## key step: making the "se" (SummarizedExperiment) object
data_se <- make_se(data_unique, LFQ_columns, MDAMB_metadata_for_exp_design)
```

```{r}
plot_frequency(data_se)
```

```{r}
plot_numbers(data_se)
```

```{r}
plot_coverage(data_se)
```

```{r}
data_norm <- normalize_vsn(data_se)
```

```{r}
plot_normalization(data_se, data_norm)
```

```{r}
plot_missval(data_se)
```

```{r}
data_imp <- impute(data_norm, fun = "MinProb", q = 0.01)
plot_imputation(data_norm, data_imp)
```

```{r}
# data_diff_all_contrasts <- test_diff(data_imp, type = "all")

# Test manually defined comparisons
data_diff_manual <- test_diff(data_imp, type = "manual", 
                              test = c("control468_vs_low468", "control231_vs_high231"))

dep <- add_rejections(data_diff_manual, alpha = 0.05, lfc = log2(1.5))
```

```{r}
plot_pca(dep, x = 1, y = 2, n = 500, point_size = 4)
```

```{r}
plot_cor(dep, significant = TRUE, lower = 0, upper = 1, pal = "Reds")
```

```{r}
plot_heatmap(dep, type = "centered", kmeans = TRUE, 
             k = 6, col_limit = 4, show_row_names = FALSE,
             indicate = c("condition", "replicate"))
```

```{r}
plot_heatmap(dep, type = "contrast", kmeans = TRUE, 
             k = 6, col_limit = 10, show_row_names = FALSE)
```

```{r}
plot_volcano(dep, contrast = "control468_vs_low468", label_size = 2, add_names = TRUE)
```

```{r}
plot_volcano(dep, contrast = "control231_vs_high231", label_size = 2, add_names = TRUE)
```
